##
##  Visopsys
##  Copyright (C) 1998-2018 J. Andrew McLaughlin
##
##  Makefile
##

BUILDDIR = ../../../build/system/headers/netinet

all:
	mkdir -p ${BUILDDIR}
	cp *.h ${BUILDDIR}

clean:
	rm -f *~
	rm -Rf ${BUILDDIR}

